name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-12, macos-11, macos-10.15, windows-2019, windows-2022]
        mongodb-version: [6.0, 5.0, 4.4, 4.2]
        include:
          # not available for ubuntu-22.04 yet
          # https://github.com/actions/virtual-environments/issues/5490
          - os: ubuntu-20.04
            mongodb-version: 6.0
          - os: ubuntu-20.04
            mongodb-version: 5.0
          - os: ubuntu-20.04
            mongodb-version: 4.4
    steps:
    - uses: actions/checkout@v2
    - uses: ./.
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - if: ${{ matrix.mongodb-version >= 6 }}
      run: |
        mongosh --eval "db.version()"

    - if: ${{ matrix.mongodb-version < 6 }}
      run: |
        mongo --eval "db.version()"
