name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, macos-10.15]
        # mongodb-version: [4.4, 4.2, 4.0, 3.6, 3.4, 3.2]
        os: [ubuntu-18.04, ubuntu-16.04]
        mongodb-version: [3.2]
    steps:
    - uses: ankane/setup-mongodb@v1
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - run: |
        mongo --eval "db.version()"
